version: '3.8'

services:
  app:
    build: .
    container_name: targetStriker_app
    restart: always
    ports:
      - "5101:3000"
    environment:
      DATABASE_URL: postgresql://myuser:mypassword@db:5432/mydatabase
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads

  db:
    image: postgres:16
    container_name: targetStriker_db
    restart: always
    ports:
      - "5400:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: